DWAPlannerROS:

  max_vel_trans: 2.5
  min_vel_trans: -2.5
  
  max_vel_x: 2.5
  min_vel_x: -2.5

  max_vel_y: 0
  min_vel_y: 0

  max_vel_theta: 2.5
  min_vel_theta: -2.5

  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_theta: 2.5
  acc_lim_trans: 2.5

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 1.0
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  path_distance_bias: 64.0     # 32.0
  goal_distance_bias: 24.0      # 24.0
  forward_point_distance: 0.2 # 0.325
  occdist_scale: 0.01            # 0.01
  # pdist_scale: 0.5

  vx_samples: 10
  vy_samples: 0
  vth_samples: 40

  # Trajectory Scoring Parameters

  

  

  

  # forward_point_distance: 0.325 # 0.325

  # stop_time_buffer: 0.2         # 0.2

  # scaling_speed: 0.20           # 0.25

  # max_scaling_factor: 0.2       # 0.2

  # publish_cost_grid: false

 

# # Oscillation Prevention Parameters

  # oscillation_reset_dist: 0.05  # default 0.05

 

# # Global Plan Parameters

#   prune_plan: false



