local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 1

  update_frequency: 5
  publish_frequency: 2
  
  
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  # origin_x: 12.4037
  # origin_y: 17.6778
  resolution: 0.05
  map_type: costmap

  # inscribed_radius: 0.22
  # circumscribed_radius: 0.22

  # plugins:
  #   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}