shutdown_costmaps: false

 
controller_frequency: 10
controller_patience: 3.0
conservative_reset_dist: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 8.0
oscillation_distance: 0.1

recovery_behavior_enabled: true # 默认true,是否启用 move_base 恢复行为以尝试清理空间
clearing_rotation_allowed: false # 默认true,仅当使用默认恢复行为有效，确定机器人在尝试清理空间时是否会尝试就地旋转

base_local_planner: "teb_local_planner/TebLocalPlannerROS"
# base_local_planner: "eband_local_planner/EBandPlannerROS"
# base_local_planner: "mpc_waypoint_tracking_controller/MPCWayPointTrackerROS"
# base_local_planner: "local_planner/LocalPlanner"



base_global_planner: "global_planner/GlobalPlanner"
# base_global_planner: "waypoint_global_planner/WaypointGlobalPlanner"



